[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_BLOBS_ENV = "main"
